const os = require("os"); const mongoose = require("mongoose");
const Result = require("../../models/HealthCheckResult"); const Audit = require("../../models/RuntimeSettingAudit");
const { getRedisClient, isRedisConnected } = require("../../config/redis"); const { getConfig } = require("../../config/env"); const { getMetricsSnapshot } = require("../metricsService");
const Queue = require("../infrastructure/QueueArchitectureService"); const Email = require("../EmailCenterService"); const Payment = require("../PaymentCenterService"); const AI = require("../AIProvidersCenterService"); const { storageService } = require("../storageService");
const PaymentHealth = require("../../models/PaymentProviderHealth"); const AIHealth = require("../../models/AIProviderHealth"); const StorageHealth = require("../../models/StorageProviderHealth"); const WorkflowJob = require("../../models/WorkflowJob"); const License = require("../../models/License"); const PluginVersion = require("../../models/PluginVersion"); const Download = require("../../models/Download");
const FeatureFlags = require("../featureFlags/FeatureFlagService"); const Security = require("../security/SecurityRuntime"); const Alerts = require("./HealthAlertFoundation");
const STATES = ["healthy", "warning", "critical", "offline", "unknown", "maintenance"];
class HealthService {
  constructor({ cacheTtlMs = 15000, intervalMs = Number(process.env.HEALTH_CHECK_INTERVAL_MS || 60000), retentionDays = Number(process.env.HEALTH_HISTORY_RETENTION_DAYS || 30) } = {}) { this.checks = new Map(); this.cache = new Map(); this.latest = new Map(); this.timer = null; this.configure({ cacheTtlMs, intervalMs, retentionDays }); this.registerDefaults(); }
  configure({ cacheTtlMs = this.cacheTtlMs, intervalMs = this.intervalMs, retentionDays = this.retentionDays } = {}) { if (!Number.isInteger(intervalMs) || intervalMs < 10000 || intervalMs > 86400000) throw new Error("Health interval must be 10 seconds to 24 hours."); if (!Number.isInteger(retentionDays) || retentionDays < 1 || retentionDays > 365) throw new Error("Health retention must be 1 to 365 days."); this.cacheTtlMs = cacheTtlMs; this.intervalMs = intervalMs; this.retentionDays = retentionDays; }
  register(definition) { if (!definition?.id || !/^[a-z][a-z0-9_.-]+$/.test(definition.id) || !definition.module || !definition.type || typeof definition.check !== "function") throw new Error("Health registration is invalid."); if (this.checks.has(definition.id)) throw new Error(`Health check '${definition.id}' is already registered.`); if (!STATES.includes(definition.failureStatus || "critical")) throw new Error("Invalid failure status."); this.checks.set(definition.id, definition); return definition; }
  registerDefaults() {
    this.register({ id: "application.runtime", module: "application", type: "version", check: async () => ({ ok: true, details: { uptimeSec: Math.round(process.uptime()), serverTime: new Date(), version: process.env.npm_package_version || "1.0.0", environment: process.env.NODE_ENV, nodeVersion: process.version, platform: process.platform, hostname: os.hostname() } }) });
    this.register({ id: "database.connection", module: "database", type: "connection", failureStatus: "offline", check: async () => { if (mongoose.connection.readyState !== 1) return { ok: false, status: "offline", message: "MongoDB is disconnected.", details: { readyState: mongoose.connection.readyState } }; const started = Date.now(); const ping = await mongoose.connection.db.command({ ping: 1 }); const admin = mongoose.connection.db.admin(); const info = await admin.serverInfo().catch(() => ({})); return { ok: ping.ok === 1, latencyMs: Date.now() - started, details: { version: info.version || "unknown", host: mongoose.connection.host, database: mongoose.connection.name, pool: mongoose.connection.client?.topology?.s?.pool?.totalConnectionCount ?? null, read: true, write: true } }; } });
    this.register({ id: "redis.connection", module: "redis", type: "connection", failureStatus: "warning", check: async () => { const config = getConfig(); if (!config.security.redisEnabled) return { ok: false, status: "warning", message: "Redis is disabled.", details: { configured: false } }; const client = getRedisClient(); const started = Date.now(); const pong = client && isRedisConnected() ? await client.ping() : null; const info = pong ? await client.info("server").catch(() => "") : ""; return { ok: pong === "PONG", latencyMs: Date.now() - started, details: { connected: isRedisConnected(), state: client?.status, version: info.match(/redis_version:([^\r\n]+)/)?.[1] || "unknown" } }; } });
    this.register({ id: "queue.workflows", module: "queues", type: "read", check: async () => { const data = await Queue.status(); const stats = data.stats || {}; return { ok: !stats.databaseDisconnected, status: stats.failed > 0 ? "warning" : undefined, details: { pending: stats.pending || 0, running: stats.running || 0, completed: stats.completed || 0, failed: stats.failed || 0, retryQueue: stats.retryQueue || 0, deadLetterQueue: await WorkflowJob.countDocuments({ status: "dead_letter" }).catch(() => 0) } }; } });
    this.register({ id: "email.smtp", module: "email", provider: "smtp", type: "connection", check: async ({ deep }) => { const r = deep ? await Email.testConnection() : await Email.health(); return { ok: ["healthy", "configured"].includes(r.status), status: r.status === "healthy" ? "healthy" : r.status === "configured" ? "warning" : "offline", latencyMs: r.durationMs || 0, message: r.error || r.lastError || "", details: { configured: r.status !== "disconnected", connected: r.connected ?? r.status === "healthy", lastSuccess: r.lastSuccessfulConnection, lastFailure: r.lastFailedConnection, lastCheck: r.lastTestTime } }; } });
    for (const provider of ["stripe", "wise", "hbl"]) this.register({ id: `payments.${provider}`, module: "payments", provider, type: "connection", check: async ({ deep }) => { const r = deep ? await Payment.test(provider) : mongoose.connection.readyState === 1 ? await PaymentHealth.findOne({ provider }).lean() : null; return { ok: Boolean(r && ["healthy", "connected"].includes(r.status)), status: !r ? "unknown" : ["healthy", "connected"].includes(r.status) ? "healthy" : "warning", latencyMs: r?.latencyMs || 0, message: r?.error || "", details: { configured: Boolean(r), connected: r?.connected, lastCheck: r?.lastTest, lastFailure: r?.lastWebhookFailure, lastSuccess: r?.lastWebhookSuccess } }; } });
    for (const provider of Object.keys(AI.PROVIDERS)) this.register({ id: `ai.${provider}`, module: "ai", provider, type: "connection", check: async ({ deep }) => { const r = deep ? await AI.test(provider) : mongoose.connection.readyState === 1 ? await AIHealth.findOne({ provider }).lean() : null; return { ok: r?.status === "healthy", status: !r ? "unknown" : r.status === "healthy" ? "healthy" : r.status === "provider_disabled" ? "warning" : "offline", latencyMs: r?.latency || r?.averageLatency || 0, message: r?.error || "", details: { configured: Boolean(r), connected: r?.connected, lastCheck: r?.lastTest, lastSuccess: r?.lastSuccessfulRequest, lastFailure: r?.lastFailedRequest } }; } });
    for (const provider of ["local", "s3", "r2", "spaces", "azure_blob", "gcs", "minio"]) this.register({ id: `storage.${provider}`, module: "storage", provider, type: "read", check: async ({ deep }) => { const r = deep ? await storageService.health(provider) : mongoose.connection.readyState === 1 ? await StorageHealth.findOne({ provider }).lean() : null; return { ok: Boolean(r && ["healthy", "connected"].includes(r.status)), status: !r ? "unknown" : ["healthy", "connected"].includes(r.status) ? "healthy" : "warning", latencyMs: r?.latency || 0, message: r?.error || "", details: { configured: Boolean(r), lastCheck: r?.lastTest, lastSuccess: r?.lastUpload || r?.lastDownload, availableSpace: r?.availableSpace } }; } });
    this.register({ id: "license.server", module: "license_server", type: "read", check: async () => this.collectionCheck(License, "licenses") }); this.register({ id: "plugin.updates", module: "plugin_updates", type: "version", check: async () => this.collectionCheck(PluginVersion, "plugin versions") }); this.register({ id: "downloads.service", module: "downloads", type: "read", check: async () => this.collectionCheck(Download, "downloads") });
    this.register({ id: "feature_flags.service", module: "feature_flags", type: "configuration", check: async () => { const flags = await FeatureFlags.getFlags(); return { ok: flags.length > 0, details: { registered: flags.length, enabled: flags.filter((x) => x.enabled).length } }; } });
    this.register({ id: "security.runtime", module: "security", type: "configuration", check: async () => { const policy = await Security.refresh(); return { ok: Object.keys(policy).length > 0, details: { policies: Object.keys(policy).length } }; } });
    this.register({ id: "api.metrics", module: "api", type: "latency", check: async () => { const metrics = getMetricsSnapshot(); return { ok: metrics.http.errorCount === 0 || metrics.http.errorCount / Math.max(metrics.http.requestCount, 1) < 0.05, status: metrics.http.avgDurationMs > 1000 ? "warning" : undefined, latencyMs: metrics.http.avgDurationMs, details: metrics.http }; } });
    this.register({ id: "scheduler.health", module: "scheduler", type: "dependency", check: async () => ({ ok: Boolean(this.timer), status: this.timer ? "healthy" : "warning", details: { running: Boolean(this.timer), intervalMs: this.intervalMs, checks: this.checks.size } }) });
  }
  async collectionCheck(Model, label) { if (mongoose.connection.readyState !== 1) return { ok: false, status: "offline", message: "Database unavailable." }; const started = Date.now(); const count = await Model.estimatedDocumentCount(); return { ok: true, latencyMs: Date.now() - started, details: { records: count, collection: label } }; }
  normalize(def, raw, started) { const status = raw.status || (raw.ok ? "healthy" : def.failureStatus || "critical"); return { checkId: def.id, module: def.module, provider: def.provider || "", type: def.type, status, healthy: status === "healthy", latencyMs: raw.latencyMs ?? Date.now() - started, message: raw.message || "", details: raw.details || {}, checkedAt: new Date(), expiresAt: new Date(Date.now() + this.retentionDays * 86400000) }; }
  async runCheck(id, options = {}) { const def = this.checks.get(id); if (!def) throw new Error(`Unknown health check '${id}'.`); if (!options.force) { const cached = this.cache.get(id); if (cached && cached.expires > Date.now()) return { ...cached.value, cached: true }; } const previous = this.latest.get(id); const started = Date.now(); let raw; try { raw = await def.check(options); } catch (error) { raw = { ok: false, status: def.failureStatus || "critical", message: error.message, details: { errorName: error.name } }; } const result = this.normalize(def, raw, started); this.latest.set(id, result); this.cache.set(id, { value: result, expires: Date.now() + this.cacheTtlMs }); if (mongoose.connection.readyState === 1) { await Result.create(result); const event = result.status === "warning" ? "health.warning" : ["critical", "offline"].includes(result.status) ? "health.critical" : previous && !previous.healthy && result.healthy ? "health.recovered" : "health.check.executed"; await Audit.create({ event, key: id, group: "monitoring", actorId: options.actorId || null, requestId: options.requestId || "", ip: options.ip || "", metadata: { status: result.status, latencyMs: result.latencyMs } }); if (def.provider && previous && previous.healthy !== result.healthy) await Audit.create({ event: `provider.${result.healthy ? "online" : "offline"}`, key: id, group: "monitoring", metadata: { provider: def.provider } }); } if (!result.healthy) Alerts.record({ checkId: id, status: result.status, message: result.message }); return result; }
  async runAll(options = {}) { const results = await Promise.all([...this.checks.keys()].map((id) => this.runCheck(id, options))); return this.aggregate(results); }
  aggregate(results) { const weights = { healthy: 100, warning: 65, unknown: 50, maintenance: 50, critical: 20, offline: 0 }; const score = results.length ? Math.round(results.reduce((sum, x) => sum + weights[x.status], 0) / results.length) : 0; const overallStatus = results.some((x) => x.status === "offline") ? "offline" : results.some((x) => x.status === "critical") ? "critical" : results.some((x) => x.status === "warning") ? "warning" : results.every((x) => x.status === "healthy") ? "healthy" : "unknown"; return { overallStatus, score, summary: Object.fromEntries(STATES.map((state) => [state, results.filter((x) => x.status === state).length])), results, generatedAt: new Date() }; }
  async systemHealth(options = {}) { if (options.force || !this.latest.size) return this.runAll(options); return this.aggregate([...this.latest.values()]); }
  async providerHealth() { const health = await this.systemHealth(); return health.results.filter((x) => x.provider); }
  async metrics() { const queue = await Queue.status(); return { ...getMetricsSnapshot(), serverTime: new Date(), environment: process.env.NODE_ENV, database: this.latest.get("database.connection")?.details || {}, redis: this.latest.get("redis.connection")?.details || {}, queue: queue.stats || {} }; }
  async history({ limit = 100, status, module } = {}) { if (mongoose.connection.readyState !== 1) return []; const filter = {}; if (status) filter.status = status; if (module) filter.module = module; return Result.find(filter).sort({ checkedAt: -1 }).limit(Math.min(Number(limit) || 100, 500)).lean(); }
  diagnostics() { return { checks: [...this.checks.values()].map(({ check, ...x }) => x), cache: { entries: this.cache.size, ttlMs: this.cacheTtlMs }, scheduler: { running: Boolean(this.timer), intervalMs: this.intervalMs }, retentionDays: this.retentionDays, alerts: Alerts.recent() }; }
  clearCache(id) { if (id) this.cache.delete(id); else this.cache.clear(); }
  startScheduler() { if (this.timer) return false; this.timer = setInterval(() => this.runAll({ force: true }).catch(() => {}), this.intervalMs); this.timer.unref?.(); return true; } stopScheduler() { if (!this.timer) return false; clearInterval(this.timer); this.timer = null; return true; }
}
module.exports = new HealthService(); module.exports.HealthService = HealthService; module.exports.STATES = STATES;
