const cors = require("cors"); const { getConfig } = require("../../config/env");
const DEFAULT_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"], DEFAULT_HEADERS = ["Content-Type", "Authorization", "X-Request-Id"];
function flatten(value) { if (Array.isArray(value)) return value.flatMap(flatten); if (value === undefined || value === null) return []; const text = String(value).trim(); if (!text) return []; if (text.startsWith("[") || text.startsWith("{")) { try { const parsed = JSON.parse(text); return Array.isArray(parsed) ? parsed.flatMap(flatten) : []; } catch { return []; } } return text.split(","); }
function normalizeOrigin(value, production = getConfig().app.isProduction) { try { const text = String(value || "").trim().replace(/\/+$/, ""); if (!text || text === "*" || /^(null|undefined)$/i.test(text) || /(your[-_. ]?(domain|app)|example\.com)/i.test(text)) return ""; const url = new URL(text); if (!["http:", "https:"].includes(url.protocol) || url.origin !== text) return ""; if (production && ["localhost", "127.0.0.1", "[::1]"].includes(url.hostname)) return ""; return url.origin; } catch { return ""; } }
function normalizeOrigins(value, production) { return [...new Set(flatten(value).map((item) => normalizeOrigin(item, production)).filter(Boolean))]; }
function environmentOrigins(env = process.env, config = getConfig()) { return normalizeOrigins([env.CORS_ORIGIN, env.CLIENT_URL, env.FRONTEND_URL, env.ALLOWED_ORIGINS, ...(config.cors.allowedOrigins || [])], config.app.isProduction); }
function runtimePolicy(value, production) { if (!value || typeof value !== "object") return null; const allowedOrigins = normalizeOrigins(value.allowedOrigins, production); if (!allowedOrigins.length) return null; const allowedMethods = Array.isArray(value.allowedMethods) ? value.allowedMethods.map((x) => String(x).trim().toUpperCase()).filter((x) => DEFAULT_METHODS.includes(x) || x === "HEAD") : DEFAULT_METHODS; const allowedHeaders = Array.isArray(value.allowedHeaders) ? value.allowedHeaders.map((x) => String(x).trim()).filter(Boolean) : DEFAULT_HEADERS; if (!allowedMethods.includes("OPTIONS") || !allowedMethods.includes("POST") || !allowedHeaders.some((x) => x.toLowerCase() === "content-type")) return null; return { allowedOrigins, allowedMethods, allowedHeaders, exposedHeaders: Array.isArray(value.exposedHeaders) ? value.exposedHeaders : ["X-Request-Id"], credentials: value.credentials !== false, preflightCacheSeconds: Number.isInteger(value.preflightCacheSeconds) && value.preflightCacheSeconds >= 0 ? value.preflightCacheSeconds : 600, source: "runtime" }; }
function resolve(runtimeValue, { env = process.env, config = getConfig() } = {}) { const runtime = runtimePolicy(runtimeValue, config.app.isProduction); if (runtime) return runtime; const origins = environmentOrigins(env, config); if (!origins.length && config.app.isProduction) throw new Error("No valid production CORS origins are configured."); return { allowedOrigins: origins.length ? origins : ["http://localhost:5173"], allowedMethods: DEFAULT_METHODS, allowedHeaders: DEFAULT_HEADERS, exposedHeaders: ["X-Request-Id"], credentials: true, preflightCacheSeconds: 600, source: origins.length ? "environment" : "development-default" }; }
function middleware(runtimeProvider, options = {}) { return cors((req, callback) => { let policy; try { policy = resolve(runtimeProvider?.(), options); } catch (error) { return callback(error); } const production = (options.config || getConfig()).app.isProduction; return callback(null, { origin: (origin, originCallback) => { if (!origin) return originCallback(null, true); const normalized = normalizeOrigin(origin, production); return originCallback(null, Boolean(normalized && policy.allowedOrigins.includes(normalized))); }, credentials: policy.credentials, methods: policy.allowedMethods, allowedHeaders: policy.allowedHeaders, exposedHeaders: policy.exposedHeaders, maxAge: policy.preflightCacheSeconds, optionsSuccessStatus: 204 }); }); }
module.exports = { resolve, middleware, normalizeOrigin, normalizeOrigins, environmentOrigins, runtimePolicy, DEFAULT_METHODS, DEFAULT_HEADERS };
