const field = (key, label, options = {}) => ({ key, label, type: "text", ...options });

const PROVIDERS = [
  { id: "stripe", name: "Stripe", category: "Payments", capabilities: ["payments", "webhooks"], fields: [field("environment", "Environment", { type: "select", options: ["sandbox", "live"] }), field("publishableKey", "Publishable Key", { env: "STRIPE_PUBLISHABLE_KEY" }), field("secretKey", "Secret Key", { secret: true, env: "STRIPE_SECRET_KEY" }), field("webhookSecret", "Webhook Secret", { secret: true, env: "STRIPE_WEBHOOK_SECRET" }), field("currency", "Currency"), field("webhookUrl", "Webhook URL", { readonly: true })] },
  { id: "wise", name: "Wise Business", category: "Payments", capabilities: ["payments", "webhooks"], fields: [field("environment", "Environment", { type: "select", options: ["sandbox", "live"] }), field("apiToken", "API Token", { secret: true, env: "WISE_API_TOKEN" }), field("profileId", "Profile ID", { env: "WISE_PROFILE_ID" }), field("webhookSecret", "Webhook Secret", { secret: true, env: "WISE_WEBHOOK_SECRET" }), field("webhookUrl", "Webhook URL", { readonly: true })] },
  { id: "jazzcash", name: "JazzCash", category: "Payments", capabilities: ["payments"], fields: [field("environment", "Environment", { type: "select", options: ["sandbox", "live"] }), field("merchantId", "Merchant ID", { env: "JAZZCASH_MERCHANT_ID" }), field("password", "Password", { secret: true, env: "JAZZCASH_PASSWORD" }), field("integritySalt", "Integrity Salt", { secret: true, env: "JAZZCASH_INTEGRITY_SALT" }), field("returnUrl", "Return URL"), field("hashVersion", "Hash Version")] },
  { id: "easypaisa", name: "EasyPaisa", category: "Payments", capabilities: ["payments"], fields: [field("environment", "Environment", { type: "select", options: ["sandbox", "live"] }), field("storeId", "Store ID", { env: "EASYPAISA_STORE_ID" }), field("username", "Username", { env: "EASYPAISA_USERNAME" }), field("password", "Password", { secret: true, env: "EASYPAISA_PASSWORD" }), field("hashKey", "Hash Key", { secret: true, env: "EASYPAISA_HASH_KEY" }), field("returnUrl", "Return URL")] },
  { id: "bank_transfer", name: "Bank Transfer", category: "Payments", capabilities: ["payments"], fields: ["bankName", "accountTitle", "accountNumber", "iban", "swift", "branch", "instructions"].map((key) => field(key, key.replace(/([A-Z])/g, " $1")) ) },
  { id: "smtp", name: "SMTP", category: "Email", capabilities: ["email"], fields: [field("host", "Host", { env: "SMTP_HOST" }), field("port", "Port", { type: "number", env: "SMTP_PORT" }), field("username", "Username", { env: "SMTP_USER" }), field("password", "Password", { secret: true, env: "SMTP_PASS" }), field("encryption", "Encryption", { type: "select", options: ["starttls", "tls", "none"] }), field("fromName", "From Name"), field("fromEmail", "From Email", { env: "SMTP_FROM" }), field("replyTo", "Reply To", { env: "SMTP_REPLY_TO" })] },
  ...["mailtrap", "resend", "sendgrid", "amazon_ses"].map((id) => ({ id, name: id.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()), category: "Email", capabilities: ["email"], fields: [field("apiKey", "API Key", { secret: true, env: `${id.toUpperCase()}_API_KEY` }), field("fromEmail", "From Email"), field("replyTo", "Reply To")] })),
  ...[["openai", "OpenAI", "OPENAI_API_KEY"], ["anthropic", "Anthropic Claude", "ANTHROPIC_API_KEY"], ["gemini", "Google Gemini", "GEMINI_API_KEY"], ["groq", "Groq", "GROQ_API_KEY"], ["openrouter", "OpenRouter", "OPENROUTER_API_KEY"], ["azure_openai", "Azure OpenAI", "AZURE_OPENAI_API_KEY"]].map(([id, name, env]) => ({ id, name, category: "AI Providers", capabilities: ["ai"], fields: [field("apiKey", "API Key", { secret: true, env }), field("organization", "Organization"), field("model", "Model"), field("temperature", "Temperature", { type: "number" }), field("maxTokens", "Max Tokens", { type: "number" }), field("timeoutMs", "Timeout", { type: "number" })] })),
  ...[["local", "Local"], ["s3", "Amazon S3"], ["r2", "Cloudflare R2"], ["azure_blob", "Azure Blob"], ["gcs", "Google Cloud Storage"]].map(([id, name]) => ({ id: `storage_${id}`, name, category: "Storage", capabilities: ["storage"], fields: [field("bucket", "Bucket"), field("region", "Region"), field("accessKey", "Access Key", { secret: true }), field("secretKey", "Secret Key", { secret: true }), field("endpoint", "Endpoint")] })),
  ...[["twilio", "Twilio"], ["vonage", "Vonage"]].map(([id, name]) => ({ id, name, category: "SMS", capabilities: ["sms"], fields: [field("accountId", "Account ID"), field("apiKey", "API Key", { secret: true }), field("apiSecret", "API Secret", { secret: true }), field("from", "From Number")] })),
  { id: "global_webhooks", name: "Global Webhook Settings", category: "Webhooks", capabilities: ["webhooks"], fields: [field("retries", "Retries", { type: "number" }), field("timeoutMs", "Timeout", { type: "number" }), field("signingSecret", "Signing Secret", { secret: true }), field("retryPolicy", "Retry Policy")] },
  ...[["github", "GitHub"], ["gitlab", "GitLab"], ["bitbucket", "Bitbucket"]].map(([id, name]) => ({ id, name, category: "Developer", capabilities: ["source_control", "release_sync"], fields: [field("token", "Access Token", { secret: true, env: `${id.toUpperCase()}_TOKEN` }), field("organization", "Organization"), field("webhookSecret", "Webhook Secret", { secret: true })] })),
];

const CATEGORIES = ["General", "Payments", "Email", "AI Providers", "Storage", "SMS", "Webhooks", "Developer", "Security"];
const get = (id) => PROVIDERS.find((provider) => provider.id === id);

module.exports = { CATEGORIES, PROVIDERS, get };
