const field = (key, label, options = {}) => ({ key, label, type: "text", ...options });

const PROVIDERS = [
  { id: "stripe", code: "STRIPE", name: "Stripe Checkout", category: "Payments", capabilities: ["checkout", "webhooks", "refunds"], supportedModes: ["test", "live"], supportedCurrencies: ["USD", "PKR", "EUR", "GBP"], fields: [field("environment", "Mode", { type: "select", options: ["test", "live"], required: true, description: "Use Test until a complete test checkout and webhook have succeeded." }), field("publishableKey", "Publishable Key", { env: "STRIPE_PUBLISHABLE_KEY", required: true, description: "Starts with pk_test_ or pk_live_." }), field("secretKey", "Secret Key", { secret: true, env: "STRIPE_SECRET_KEY", required: true, description: "Starts with sk_test_ or sk_live_." }), field("webhookSecret", "Webhook Secret", { secret: true, env: "STRIPE_WEBHOOK_SECRET", required: true, description: "Signing secret from the Stripe webhook endpoint." }), field("currency", "Default Currency", { type: "select", options: ["USD", "PKR", "EUR", "GBP"], required: true }), field("successUrl", "Success URL", { required: true, description: "Customer return page after hosted checkout." }), field("cancelUrl", "Cancel URL", { required: true, description: "Customer return page after checkout cancellation." }), field("webhookUrl", "Webhook URL", { readonly: true, description: "Copy this exact URL into the Stripe webhook endpoint." })] },
  { id: "wise_business", code: "WISE_BUSINESS", name: "Wise Business", category: "Payments", capabilities: ["capability_detection"], supportedModes: ["sandbox", "live"], supportedCurrencies: ["USD", "PKR", "EUR", "GBP"], fields: [field("environment", "Environment", { type: "select", options: ["sandbox", "live"], required: true }), field("apiToken", "API Token", { secret: true, env: "WISE_API_TOKEN", required: true }), field("profileId", "Profile ID", { env: "WISE_PROFILE_ID", required: true }), field("webhookSubscriptionId", "Webhook Subscription ID"), field("webhookSecret", "Webhook Verification Secret", { secret: true, env: "WISE_WEBHOOK_SECRET" }), field("accountCurrency", "Account Currency"), field("returnUrl", "Return URL", { readonly: true }), field("webhookUrl", "Webhook URL", { readonly: true })] },
  { id: "hblpay_checkout", code: "HBLPAY_CHECKOUT", name: "HBLPay Checkout", category: "Payments", capabilities: ["merchant_contract_required"], supportedModes: ["sandbox", "live"], supportedCurrencies: ["PKR"], fields: [field("environment", "Mode", { type: "select", options: ["sandbox", "live"], required: true }), field("merchantId", "Merchant ID", { required: true }), field("storeId", "Store / Channel ID"), field("username", "Username"), field("password", "Password / Secret", { secret: true, required: true }), field("integrityKey", "Hash / Integrity Key", { secret: true, required: true }), field("baseUrl", "API / Base URL", { required: true }), field("currency", "Default Currency", { readonly: true }), field("returnUrl", "Return URL", { readonly: true }), field("webhookUrl", "Callback URL", { readonly: true })] },
  { id: "smtp", name: "SMTP", category: "Email", capabilities: ["email"], fields: [field("host", "Host", { env: "SMTP_HOST" }), field("port", "Port", { type: "number", env: "SMTP_PORT" }), field("username", "Username", { env: "SMTP_USER" }), field("password", "Password", { secret: true, env: "SMTP_PASS" }), field("encryption", "Encryption", { type: "select", options: ["starttls", "tls", "none"] }), field("fromName", "From Name"), field("fromEmail", "From Email", { env: "SMTP_FROM" }), field("replyTo", "Reply To", { env: "SMTP_REPLY_TO" })] },
  ...["mailtrap", "resend", "sendgrid", "amazon_ses"].map((id) => ({ id, name: id.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()), category: "Email", capabilities: ["email"], fields: [field("apiKey", "API Key", { secret: true, env: `${id.toUpperCase()}_API_KEY` }), field("fromEmail", "From Email"), field("replyTo", "Reply To")] })),
  ...[["openai", "OpenAI", "OPENAI_API_KEY"], ["anthropic", "Anthropic Claude", "ANTHROPIC_API_KEY"], ["gemini", "Google Gemini", "GEMINI_API_KEY"], ["groq", "Groq", "GROQ_API_KEY"], ["openrouter", "OpenRouter", "OPENROUTER_API_KEY"], ["azure_openai", "Azure OpenAI", "AZURE_OPENAI_API_KEY"]].map(([id, name, env]) => ({ id, name, category: "AI Providers", capabilities: ["ai"], fields: [field("apiKey", "API Key", { secret: true, env }), field("organization", "Organization"), field("model", "Model"), field("temperature", "Temperature", { type: "number" }), field("maxTokens", "Max Tokens", { type: "number" }), field("timeoutMs", "Timeout", { type: "number" })] })),
  ...[["local", "Local"], ["s3", "Amazon S3"], ["r2", "Cloudflare R2"], ["azure_blob", "Azure Blob"], ["gcs", "Google Cloud Storage"]].map(([id, name]) => ({ id: `storage_${id}`, name, category: "Storage", capabilities: ["storage"], fields: [field("bucket", "Bucket"), field("region", "Region"), field("accessKey", "Access Key", { secret: true }), field("secretKey", "Secret Key", { secret: true }), field("endpoint", "Endpoint")] })),
  ...[["twilio", "Twilio"], ["vonage", "Vonage"]].map(([id, name]) => ({ id, name, category: "SMS", capabilities: ["sms"], fields: [field("accountId", "Account ID"), field("apiKey", "API Key", { secret: true }), field("apiSecret", "API Secret", { secret: true }), field("from", "From Number")] })),
  { id: "global_webhooks", name: "Global Webhook Settings", category: "Webhooks", capabilities: ["webhooks"], fields: [field("retries", "Retries", { type: "number" }), field("timeoutMs", "Timeout", { type: "number" }), field("signingSecret", "Signing Secret", { secret: true }), field("retryPolicy", "Retry Policy")] },
  ...[["github", "GitHub"], ["gitlab", "GitLab"], ["bitbucket", "Bitbucket"]].map(([id, name]) => ({ id, name, category: "Developer", capabilities: ["source_control", "release_sync"], fields: [field("token", "Access Token", { secret: true, env: `${id.toUpperCase()}_TOKEN` }), field("organization", "Organization"), field("webhookSecret", "Webhook Secret", { secret: true })] })),
];

const CATEGORIES = ["General", "Payments", "Email", "AI Providers", "Storage", "SMS", "Webhooks", "Developer", "Security"];
const get = (id) => PROVIDERS.find((provider) => provider.id === id);

module.exports = { CATEGORIES, PROVIDERS, get };
