const crypto = require("crypto");
const mongoose = require("mongoose");
const FeatureFlag = require("../../models/FeatureFlag");
const RuntimeSettingAudit = require("../../models/RuntimeSettingAudit");
const { CATALOG, MAINTENANCE_DEFAULT } = require("../../config/featureFlagCatalog");
const { AppError } = require("../../utils/errorHandler");
class FeatureFlagService {
  constructor() { this.cache = new Map(); this.registered = new Map(CATALOG.map((f) => [f.key, f])); }
  async register(definition) { if (!definition?.key || !/^[a-z][a-z0-9_.-]{2,119}$/.test(definition.key)) throw new AppError("Feature key is invalid.", 422); if (this.registered.has(definition.key) && !CATALOG.some((f) => f.key === definition.key)) throw new AppError("Feature key already exists.", 409); this.registered.set(definition.key, definition); if (mongoose.connection.readyState === 1) await FeatureFlag.updateOne({ key: definition.key }, { $setOnInsert: { ...definition, enabled: definition.defaultValue, rolloutPercentage: 100 } }, { upsert: true }); return definition; }
  async ensureCatalog() { if (mongoose.connection.readyState !== 1) return; await Promise.all(CATALOG.map((flag) => FeatureFlag.updateOne({ key: flag.key }, { $setOnInsert: { ...flag, enabled: flag.defaultValue, description: flag.description || `${flag.name} runtime toggle.`, rolloutPercentage: 100 } }, { upsert: true }))); }
  fallback(key) { const item = this.registered.get(key); return item ? { environmentRules: [], allowedRoles: [], allowedUserIds: [], allowedPlans: [], dependencies: [], emergencyKillSwitch: false, rolloutPercentage: 100, ...item, enabled: item.enabled ?? item.defaultValue, dependencies: item.dependencies || [] } : null; }
  async getFlag(key) { if (this.cache.has(`flag:${key}`)) return this.cache.get(`flag:${key}`); await this.ensureCatalog(); const flag = mongoose.connection.readyState === 1 ? await FeatureFlag.findOne({ key }).lean() : null; const value = flag || this.fallback(key); if (!value) throw new AppError("Feature flag not found.", 404); this.cache.set(`flag:${key}`, value); return value; }
  async getFlags(filter = {}) { await this.ensureCatalog(); let flags = mongoose.connection.readyState === 1 ? await FeatureFlag.find({}).populate("updatedBy", "name email").sort({ category: 1, key: 1 }).lean() : CATALOG.map((x) => this.fallback(x.key)); if (filter.category) flags = flags.filter((x) => x.category === filter.category); if (filter.search) { const q = filter.search.toLowerCase(); flags = flags.filter((x) => `${x.key} ${x.name} ${x.description}`.toLowerCase().includes(q)); } return flags; }
  async getGroup(category) { return this.getFlags({ category }); }
  bucket(key, subject) { const digest = crypto.createHash("sha256").update(`${key}:${subject}`).digest(); return digest.readUInt32BE(0) % 100; }
  async evaluate(key, context = {}, stack = new Set()) { const cacheKey = `eval:${key}:${JSON.stringify({ environment: context.environment, role: context.role, userId: context.userId, plan: context.plan, ip: context.ip })}`; if (this.cache.has(cacheKey)) return this.cache.get(cacheKey); if (stack.has(key)) throw new AppError(`Circular feature dependency detected at ${key}.`, 422); stack.add(key); const flag = await this.getFlag(key); let reason = "default"; let enabled = Boolean(flag.enabled ?? flag.defaultValue);
    if (flag.emergencyKillSwitch) { enabled = false; reason = "emergency_kill_switch"; }
    else if (key !== "maintenance.global" && await this.isMaintenanceActive(context)) { enabled = false; reason = "maintenance_mode"; }
    else { const envRule = (flag.environmentRules || []).find((r) => r.environment === (context.environment || process.env.NODE_ENV)); if (envRule) { enabled = envRule.enabled; reason = "environment_rule"; } if (enabled && flag.allowedRoles?.length) { enabled = flag.allowedRoles.includes(context.role); reason = "role_rule"; } if (enabled && flag.allowedUserIds?.length) { enabled = flag.allowedUserIds.includes(String(context.userId || "")); reason = "user_rule"; } if (enabled && flag.allowedPlans?.length) { enabled = flag.allowedPlans.includes(String(context.plan || "")); reason = "plan_rule"; } if (enabled && flag.rolloutPercentage < 100) { enabled = flag.rolloutPercentage > 0 && this.bucket(key, context.userId || context.ip || "anonymous") < flag.rolloutPercentage; reason = "percentage_rollout"; } const now = Date.now(); if (enabled && flag.scheduledActivation && now < new Date(flag.scheduledActivation).getTime()) { enabled = false; reason = "not_started"; } if (enabled && flag.scheduledExpiration && now >= new Date(flag.scheduledExpiration).getTime()) { enabled = false; reason = "expired"; } }
    if (enabled) for (const dependency of flag.dependencies || []) { const result = await this.evaluate(dependency, context, stack); if (!result.enabled) { enabled = false; reason = `dependency:${dependency}`; break; } } stack.delete(key); const result = { key, enabled, reason, rolloutPercentage: flag.rolloutPercentage, evaluatedAt: new Date() }; this.cache.set(cacheKey, result); return result; }
  async isEnabled(key, context = {}) { return (await this.evaluate(key, context)).enabled; }
  validatePatch(current, patch) { const next = { ...current, ...patch }; if (!Number.isFinite(Number(next.rolloutPercentage)) || next.rolloutPercentage < 0 || next.rolloutPercentage > 100) throw new AppError("Rollout percentage must be from 0 to 100.", 422); if (next.scheduledActivation && next.scheduledExpiration && new Date(next.scheduledActivation) >= new Date(next.scheduledExpiration)) throw new AppError("Scheduled activation must be before expiration.", 422); const environments = next.environmentRules || []; if (new Set(environments.map((x) => x.environment)).size !== environments.length || environments.some((x) => !["development", "test", "staging", "production"].includes(x.environment))) throw new AppError("Environment rules are invalid or duplicated.", 422); if ((next.dependencies || []).includes(next.key)) throw new AppError("A feature cannot depend on itself.", 422); for (const dependency of next.dependencies || []) if (!this.registered.has(dependency)) throw new AppError(`Unknown dependency: ${dependency}`, 422); return next; }
  async update(key, patch, context = {}) { const current = await this.getFlag(key); const next = this.validatePatch(current, patch); if (next.enabled) for (const dependency of next.dependencies || []) if (!(await this.isEnabled(dependency, context))) throw new AppError(`Enable dependency '${dependency}' first.`, 409); let saved = next; if (mongoose.connection.readyState === 1) saved = await FeatureFlag.findOneAndUpdate({ key }, { $set: { ...patch, updatedBy: context.actorId || null } }, { new: true, runValidators: true }).lean(); this.clearCache(key); const event = patch.emergencyKillSwitch !== undefined ? `kill_switch.${patch.emergencyKillSwitch ? "enabled" : "disabled"}` : patch.rolloutPercentage !== undefined && patch.rolloutPercentage !== current.rolloutPercentage ? "feature.rollout.changed" : patch.enabled !== undefined && patch.enabled !== current.enabled ? `feature.${patch.enabled ? "enabled" : "disabled"}` : "feature.updated"; if (mongoose.connection.readyState === 1) await RuntimeSettingAudit.create({ event, key, group: "featureFlags", actorId: context.actorId, requestId: context.requestId, ip: context.ip, metadata: { previous: current, changes: patch } }); return saved; }
  enable(key, context) { return this.update(key, { enabled: true }, context); } disable(key, context) { return this.update(key, { enabled: false }, context); }
  async reload(key) { this.clearCache(key); return key ? this.getFlag(key) : this.getFlags(); }
  clearCache(key) { if (!key) return this.cache.clear(); for (const cacheKey of this.cache.keys()) if (cacheKey === `flag:${key}` || cacheKey.startsWith(`eval:${key}:`) || cacheKey.startsWith("eval:")) this.cache.delete(cacheKey); }
  async maintenance() { const flag = await this.getFlag("maintenance.global"); return { ...MAINTENANCE_DEFAULT, ...(flag.metadata?.maintenance || {}), enabled: Boolean(flag.enabled), emergencyKillSwitch: flag.emergencyKillSwitch, updatedAt: flag.updatedAt, updatedBy: flag.updatedBy }; }
  async isMaintenanceActive(context = {}) { const m = await this.maintenance(); if (!m.enabled) return false; const now = Date.now(); if (m.scheduledStart && now < new Date(m.scheduledStart).getTime()) return false; if (m.scheduledEnd && now >= new Date(m.scheduledEnd).getTime()) return false; if (m.allowedRoles.includes(context.role) || m.allowedIps.includes(context.ip)) return false; return true; }
  async updateMaintenance(patch, context = {}) { const current = await this.maintenance(); const next = { ...current, ...patch }; if (next.scheduledStart && next.scheduledEnd && new Date(next.scheduledStart) >= new Date(next.scheduledEnd)) throw new AppError("Maintenance start must be before its end.", 422); const saved = await this.update("maintenance.global", { enabled: next.enabled, metadata: { maintenance: next } }, context); if (mongoose.connection.readyState === 1) await RuntimeSettingAudit.create({ event: `maintenance.${next.enabled ? "enabled" : "disabled"}`, key: "maintenance.global", group: "featureFlags", actorId: context.actorId, requestId: context.requestId, ip: context.ip }); return saved; }
}
module.exports = new FeatureFlagService(); module.exports.FeatureFlagService = FeatureFlagService;
