const assert = require("assert"); const http = require("http"); const express = require("express"); process.env.NODE_ENV = "test"; process.env.MONGO_URI = "mongodb://127.0.0.1/test"; process.env.JWT_ACCESS_SECRET = "cors-regression-access-secret"; process.env.JWT_REFRESH_SECRET = "cors-regression-refresh-secret"; process.env.APP_ENCRYPTION_KEY = "cors-regression-encryption-key-32-chars";
const Cors = require("../src/services/security/CorsPolicyResolver"); const { maintenanceGuard } = require("../src/middleware/featureFlagRuntime");
const vercel = "https://parentheses-licence.vercel.app"; const prodConfig = { app: { isProduction: true }, cors: { allowedOrigins: [] } }; const devConfig = { app: { isProduction: false }, cors: { allowedOrigins: [] } }; const env = { CLIENT_URL: vercel };
function policy(origins) { return { allowedOrigins: origins, allowedMethods: ["GET", "POST", "OPTIONS"], allowedHeaders: ["Content-Type", "Authorization"], exposedHeaders: ["X-Request-Id"], credentials: true, preflightCacheSeconds: 600 }; }
async function withApp(runtimeValue, options, callback) { const app = express(); app.use(Cors.middleware(() => runtimeValue, options)); app.use(express.json()); app.post("/api/v1/auth/login", (req, res) => res.status(401).json({ reached: true })); app.get("/error", () => { throw new Error("expected"); }); app.use((error, req, res, next) => { void next; res.status(500).json({ message: error.message }); }); const server = http.createServer(app); await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve)); try { await callback(server.address().port); } finally { await new Promise((resolve) => server.close(resolve)); } }
function request(port, { method = "OPTIONS", path = "/api/v1/auth/login", origin = vercel, headers = {}, body } = {}) { return new Promise((resolve, reject) => { const req = http.request({ host: "127.0.0.1", port, method, path, headers: { Origin: origin, ...(method === "OPTIONS" ? { "Access-Control-Request-Method": "POST", "Access-Control-Request-Headers": "content-type,authorization" } : {}), ...(body ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body) } : {}), ...headers } }, (res) => { let data = ""; res.on("data", (chunk) => { data += chunk; }); res.on("end", () => resolve({ status: res.statusCode, headers: res.headers, body: data })); }); req.on("error", reject); if (body) req.write(body); req.end(); }); }
(async () => {
  const absent = Cors.resolve(undefined, { env, config: prodConfig }); assert.deepStrictEqual(absent.allowedOrigins, [vercel]); assert.strictEqual(absent.source, "environment");
  for (const empty of [null, undefined, { allowedOrigins: [] }, { allowedOrigins: "" }, { allowedOrigins: null }, { allowedOrigins: "[malformed" }, policy(["https://example.com"])]) assert.deepStrictEqual(Cors.resolve(empty, { env, config: prodConfig }).allowedOrigins, [vercel]);
  const dbOrigin = "https://admin.parentheses.test"; const db = Cors.resolve(policy([`${dbOrigin}/`]), { env, config: prodConfig }); assert.deepStrictEqual(db.allowedOrigins, [dbOrigin]); assert.strictEqual(db.source, "runtime");
  assert.deepStrictEqual(Cors.resolve(undefined, { env: {}, config: devConfig }).allowedOrigins, ["http://localhost:5173"]); assert.throws(() => Cors.resolve(policy(["http://localhost:5173"]), { env: {}, config: prodConfig }), /No valid production/);
  await withApp(undefined, { env, config: prodConfig }, async (port) => { const preflight = await request(port, {}); assert.strictEqual(preflight.status, 204); assert.strictEqual(preflight.headers["access-control-allow-origin"], vercel); assert.strictEqual(preflight.headers["access-control-allow-credentials"], "true"); assert.ok(preflight.headers["access-control-allow-methods"].includes("POST")); assert.ok(preflight.headers["access-control-allow-headers"].toLowerCase().includes("content-type")); const login = await request(port, { method: "POST", body: "{}" }); assert.strictEqual(login.status, 401); assert.strictEqual(JSON.parse(login.body).reached, true); assert.strictEqual(login.headers["access-control-allow-origin"], vercel); const denied = await request(port, { origin: "https://evil.invalid" }); assert.strictEqual(denied.headers["access-control-allow-origin"], undefined); for (let index = 0; index < 20; index += 1) assert.strictEqual((await request(port, {})).status, 204); const error = await request(port, { method: "GET", path: "/error" }); assert.strictEqual(error.status, 500); assert.strictEqual(error.headers["access-control-allow-origin"], vercel); });
  await withApp(undefined, { env: {}, config: devConfig }, async (port) => assert.strictEqual((await request(port, { origin: "http://localhost:5173" })).headers["access-control-allow-origin"], "http://localhost:5173"));
  let maintenanceNext = false; await maintenanceGuard({ method: "OPTIONS", path: "/x", originalUrl: "/api/v1/protected", headers: {}, ip: "127.0.0.1" }, {}, () => { maintenanceNext = true; }); assert.strictEqual(maintenanceNext, true);
  const appSource = require("fs").readFileSync(require("path").join(__dirname, "../src/app.js"), "utf8"); assert.ok(appSource.indexOf("app.use(CorsPolicyResolver.middleware") < appSource.indexOf("app.use(RuntimeSecurity.load")); assert.ok(appSource.indexOf("app.use(CorsPolicyResolver.middleware") < appSource.indexOf("app.use(maintenanceGuard")); assert.ok(appSource.indexOf("app.use(CorsPolicyResolver.middleware") < appSource.indexOf("app.use(RuntimeSecurity.rate"));
  console.log("PASS Phase 16 production CORS regression tests"); process.exit(0);
})().catch((error) => { console.error(error); process.exit(1); });
