const assert = require("assert"); process.env.NODE_ENV = "test"; process.env.MONGO_URI = "mongodb://127.0.0.1/test"; process.env.JWT_ACCESS_SECRET = "phase16j-access-secret"; process.env.JWT_REFRESH_SECRET = "phase16j-refresh-secret"; process.env.APP_ENCRYPTION_KEY = "phase16j-encryption-key-with-32-characters";
const { ConfigurationManager, checksum } = require("../src/services/configuration/ConfigurationManager"); const Diff = require("../src/services/configuration/ConfigurationDiffEngine");
(async () => { const manager = new ConfigurationManager({ maximumSnapshots: 5, retentionDays: 30 }); const payload = await manager.capture({ keys: ["general.portalName", "security.jwt"], includeSecrets: true }); assert.strictEqual(payload.schemaVersion, 1); assert.ok(payload.settings["general.portalName"]); const packed = manager.pack(payload); assert.strictEqual(manager.unpack(packed.envelope).settings["general.portalName"].value, payload.settings["general.portalName"].value); assert.strictEqual(packed.checksum, checksum(JSON.stringify(payload))); assert.throws(() => manager.unpack({ ...packed.envelope, ciphertext: `${packed.envelope.ciphertext.slice(0, -4)}AAAA` }));
  const a = { settings: { "a.one": { value: 1 }, "b.two": { value: 2 }, "same.key": { value: true } } }; const b = { settings: { "a.one": { value: 3 }, "c.three": { value: 4 }, "same.key": { value: true } } }; const diff = Diff.compare(a, b); assert.strictEqual(diff.summary.added, 1); assert.strictEqual(diff.summary.removed, 1); assert.strictEqual(diff.summary.changed, 1); assert.strictEqual(diff.summary.unchanged, 1);
  const valid = manager.validatePayload(payload); assert.strictEqual(valid.valid, true); const invalid = manager.validatePayload({ ...payload, schemaVersion: 99 }); assert.strictEqual(invalid.valid, false); const unknown = manager.validatePayload({ ...payload, settings: { "unknown.key": { value: true, group: "invalid" } } }); assert.strictEqual(unknown.valid, false);
  const encryptedExport = await manager.export({ encrypted: true }); assert.strictEqual(encryptedExport.format, "encrypted-json"); assert.strictEqual(manager.decodeImport(encryptedExport).schemaVersion, 1); const tampered = { ...encryptedExport, checksum: "0".repeat(64) }; assert.throws(() => manager.decodeImport(tampered), /checksum/);
  class Harness extends ConfigurationManager { constructor() { super({ maximumSnapshots: 5, retentionDays: 30 }); this.events = []; this.applied = []; this.target = payload; } async acquire(op) { this.events.push(`lock:${op}`); } async release() { this.events.push("release"); } async backup(options) { this.events.push(`backup:${options.type}`); return { _id: "pre" }; } async currentPayload() { return a; } async snapshotPayload() { return { snapshot: { _id: "target" }, payload: this.target }; } async apply(next, scope, context) { this.applied.push({ next, scope, operation: context.operation }); return Object.keys(next.settings); } async audit(event) { this.events.push(event); } }
  const harness = new Harness(); const restored = await harness.restore("target", { confirm: true }, { actorId: "actor" }); assert.strictEqual(restored.restored, true); assert.ok(harness.events.includes("configuration.restored")); assert.ok(harness.events.includes("release")); const rolled = await harness.rollback("target", { confirm: true }, { actorId: "actor" }); assert.strictEqual(rolled.restored, true); assert.ok(harness.events.includes("configuration.rollback")); await assert.rejects(() => harness.restore("target", {}, {}), /confirmation/); await assert.rejects(() => harness.rollback("target", {}, {}), /confirmation/);
  const importer = new Harness(); importer.diff = async () => diff; const preview = await importer.import(payload, { preview: true }, {}); assert.strictEqual(preview.validation.valid, true); const imported = await importer.import(payload, { confirm: true }, { actorId: "actor" }); assert.ok(imported.imported > 0); assert.ok(importer.events.includes("configuration.imported"));
  class FailureHarness extends Harness { async apply(next, scope, context) { this.applied.push({ next, operation: context.operation }); if (context.operation === "restore") throw new Error("restore failed"); return []; } } const failure = new FailureHarness(); await assert.rejects(() => failure.restore("target", { confirm: true }, {}), /restore failed/); assert.ok(failure.applied.some((x) => x.operation === "automatic_rollback"));
  assert.throws(() => new ConfigurationManager({ maximumSnapshots: 0, retentionDays: 30 }), /Maximum/); assert.throws(() => new ConfigurationManager({ maximumSnapshots: 5, retentionDays: 0 }), /Retention/);
  const routes = require("../src/routes/adminConfiguration").stack.filter((x) => x.route).map((x) => x.route.path); ["/snapshots", "/backup", "/restore", "/import", "/export", "/versions", "/diff", "/rollback", "/validate", "/recovery"].forEach((path) => assert.ok(routes.includes(path)));
  const Audit = require("../src/models/RuntimeSettingAudit"); ["configuration.backup.created", "configuration.backup.deleted", "configuration.exported", "configuration.imported", "configuration.restored", "configuration.rollback", "configuration.integrity.failed", "configuration.recovery.executed"].forEach((event) => assert.strictEqual(new Audit({ event }).validateSync(), undefined));
  console.log("PASS Phase 16J Enterprise Configuration Management tests"); process.exit(0);
})().catch((error) => { console.error(error); process.exit(1); });
