const asyncHandler = require("express-async-handler");
const settings = require("../services/settings");
const runtime = require("../services/security/SecurityRuntime");
const { AppError } = require("../utils/errorHandler");
const User = require("../models/User");
const eventFor = (key) => key === "security.password" ? "password.policy.updated" : key === "security.jwt" ? "jwt.updated" : key === "security.sessions" ? "session.updated" : key.startsWith("security.rateLimits") ? "rate_limit.updated" : key === "security.cors" ? "cors.updated" : key === "security.headers" ? "security.header.updated" : "security.settings.updated";
const context = (req, key) => ({ actorId: req.user._id, requestId: req.id, ip: req.ip, auditEvent: eventFor(key) });
exports.get = asyncHandler(async (req, res) => { const data = {}; for (const definition of settings.definitions.getGroup("security")) { const result = await settings.get(definition.key, { withMetadata: true }); data[definition.key] = { value: result.value, source: result.source, label: definition.label, description: definition.description, section: definition.ui.section }; } res.json({ success: true, data }); });
exports.patch = asyncHandler(async (req, res) => { const entries = Object.entries(req.body.settings || {}); if (!entries.length) throw new AppError("At least one security setting is required.", 422); for (const [key, value] of entries) { if (!key.startsWith("security.") || !settings.definitions.has(key)) throw new AppError(`Invalid security setting: ${key}`, 422); const previous = key === "security.ip" ? await settings.get(key) : null; await settings.set(key, value, context(req, key)); if (previous) { const before = new Set([...(previous.blockList || []), ...(previous.permanentBlocks || [])]); const after = new Set([...(value.blockList || []), ...(value.permanentBlocks || [])]); for (const ip of after) if (!before.has(ip)) await settings.repository.audit("ip.blocked", { key, group: "security", actorId: req.user._id, requestId: req.id, ip: req.ip, metadata: { blockedIp: ip } }); for (const ip of before) if (!after.has(ip)) await settings.repository.audit("ip.unblocked", { key, group: "security", actorId: req.user._id, requestId: req.id, ip: req.ip, metadata: { unblockedIp: ip } }); } } await runtime.refresh(); res.json({ success: true, message: "Security settings updated.", data: runtime.current() }); });
function score(policy) { const checks = [policy["security.authentication"]?.enabled, policy["security.password"]?.minimumLength >= 12, policy["security.password"]?.preventCommonPasswords, policy["security.sessions"]?.idleTimeoutMs > 0, policy["security.jwt"]?.tokenRotation, policy["security.rateLimits.api"]?.enabled, policy["security.cors"]?.allowedOrigins?.length > 0, Boolean(policy["security.headers"]?.contentSecurityPolicy), policy["security.cookies"]?.httpOnly, policy["security.cookies"]?.secure]; return Math.round(checks.filter(Boolean).length / checks.length * 100); }
exports.health = asyncHandler(async (req, res) => { const policy = await runtime.refresh(); const status = (ok) => ok ? "healthy" : "attention_required"; res.json({ success: true, data: { overallSecurityScore: score(policy), authenticationStatus: status(policy["security.authentication"]?.enabled), jwtStatus: status(policy["security.jwt"]?.tokenRotation), rateLimitingStatus: status(policy["security.rateLimits.api"]?.enabled), corsStatus: status(policy["security.cors"]?.allowedOrigins?.length), headerStatus: status(policy["security.headers"]?.contentSecurityPolicy), sessionStatus: status(policy["security.sessions"]?.idleTimeoutMs), passwordPolicyStatus: status(policy["security.password"]?.minimumLength >= 8), evaluatedAt: new Date() } }); });
exports.policies = asyncHandler(async (req, res) => res.json({ success: true, data: await runtime.refresh() }));
exports.forceLogout = asyncHandler(async (req, res) => { const result = await User.updateMany({ "refreshSessions.0": { $exists: true } }, { $set: { refreshSessions: [] } }); await settings.repository.audit("session.updated", { actorId: req.user._id, requestId: req.id, ip: req.ip, metadata: { action: "force_logout", users: result.modifiedCount } }); res.json({ success: true, message: "All refresh sessions invalidated.", data: { users: result.modifiedCount } }); });
