const SettingsRepository = require("./SettingsRepository");
const SettingsService = require("./SettingsService");
const { SettingDefinitionRegistry, GROUPS } = require("./SettingDefinitionRegistry");
const definitions = new SettingDefinitionRegistry();
require("./GeneralSettingDefinitions").registerGeneralSettings(definitions);
require("./EmailSettingDefinitions").registerEmailSettings(definitions);
require("./PaymentSettingDefinitions").registerPaymentSettings(definitions);
require("./AIProviderSettingDefinitions").registerAIProviderSettings(definitions);
require("./StorageSettingDefinitions").registerStorageSettings(definitions);
require("./SecuritySettingDefinitions").registerSecuritySettings(definitions);
const service = new SettingsService({ repository: new SettingsRepository(), definitions });
module.exports = service;
module.exports.SettingsService = SettingsService;
module.exports.SettingsRepository = SettingsRepository;
module.exports.SettingDefinitionRegistry = SettingDefinitionRegistry;
module.exports.GROUPS = GROUPS;
module.exports.definitions = definitions;
module.exports.validators = require("./SettingValidators");
module.exports.errors = require("./errors");
