const net = require("net");
const ok = (value) => ({ valid: true, value });
const fail = (message) => ({ valid: false, message });
const integer = (min, max) => (value) => Number.isInteger(Number(value)) && Number(value) >= min && Number(value) <= max ? ok(Number(value)) : fail(`must be an integer from ${min} to ${max}`);
const stringList = (test, label) => (value) => Array.isArray(value) && value.every((item) => typeof item === "string" && test(item)) ? ok([...new Set(value.map((item) => item.trim()))]) : fail(`must be an array of valid ${label}`);
const origin = (value) => { try { const url = new URL(value); return ["http:", "https:"].includes(url.protocol) && url.origin === value; } catch { return false; } };
const cidr = (value) => { const [ip, bits] = String(value).split("/"); const family = net.isIP(ip); return Boolean(family && (bits === undefined || (/^\d+$/.test(bits) && Number(bits) <= (family === 4 ? 32 : 128)))); };
const headerName = (value) => /^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/.test(value);
const duration = integer(1, 31_536_000_000);
const DEFINITIONS = [
  ["security.authentication", { enabled: true, requireEmailVerification: true }, "object"],
  ["security.password", { minimumLength: 8, maximumLength: 128, uppercaseRequired: true, lowercaseRequired: true, numberRequired: true, specialCharacterRequired: true, historyCount: 5, expirationDays: 0, preventCommonPasswords: true, preventUsernameUsage: true }, (v) => v && integer(8, 256)(v.minimumLength).valid && integer(8, 256)(v.maximumLength).valid && v.maximumLength >= v.minimumLength && integer(0, 24)(v.historyCount).valid && integer(0, 3650)(v.expirationDays).valid ? ok(v) : fail("contains invalid or inconsistent password rules")],
  ["security.sessions", { sessionTimeoutMs: 86400000, rememberMeDurationMs: 604800000, maximumConcurrentSessions: 5, idleTimeoutMs: 1800000, absoluteTimeoutMs: 604800000, invalidateOnPasswordChange: true }, (v) => v && [v.sessionTimeoutMs, v.rememberMeDurationMs, v.idleTimeoutMs, v.absoluteTimeoutMs].every((x) => duration(x).valid) && integer(1, 100)(v.maximumConcurrentSessions).valid ? ok(v) : fail("contains invalid session durations or limits")],
  ["security.jwt", { accessTokenLifetime: "15m", refreshTokenLifetime: "7d", tokenRotation: true, refreshPolicy: "rotate", clockSkewSeconds: 30, signingAlgorithm: "HS256" }, (v) => v && /^\d+(s|m|h|d)$/.test(v.accessTokenLifetime) && /^\d+(s|m|h|d)$/.test(v.refreshTokenLifetime) && ["rotate", "reuse"].includes(v.refreshPolicy) && integer(0, 300)(v.clockSkewSeconds).valid && v.signingAlgorithm === "HS256" ? ok(v) : fail("contains invalid JWT configuration")],
  ...["login", "registration", "passwordReset", "verificationEmail", "api", "webhook", "admin"].map((name) => [`security.rateLimits.${name}`, { enabled: true, limit: name === "api" ? 300 : name === "admin" ? 180 : 10, burst: 5, windowMs: name === "api" ? 900000 : 60000 }, (v) => v && integer(1, 100000)(v.limit).valid && integer(0, 10000)(v.burst).valid && duration(v.windowMs).valid ? ok(v) : fail("contains invalid rate-limit values")]),
  ["security.rateLimits.custom", {}, "object"],
  ["security.bruteForce", { maximumFailedAttempts: 5, lockoutDurationMs: 900000, progressiveDelayMs: 500, captchaThreshold: 3, adminNotifications: true }, (v) => v && integer(1, 100)(v.maximumFailedAttempts).valid && duration(v.lockoutDurationMs).valid && integer(0, 60000)(v.progressiveDelayMs).valid && integer(1, 100)(v.captchaThreshold).valid ? ok(v) : fail("contains invalid brute-force configuration")],
  ["security.ip", { allowList: [], blockList: [], trustedAdminIps: [], temporaryBlocks: [], permanentBlocks: [], countryRestrictions: [] }, (v) => v && [v.allowList, v.blockList, v.trustedAdminIps, v.permanentBlocks].every((list) => stringList(cidr, "IP/CIDR entries")(list).valid) && Array.isArray(v.temporaryBlocks) && v.temporaryBlocks.every((x) => x && cidr(x.value) && !Number.isNaN(Date.parse(x.expiresAt))) ? ok(v) : fail("contains an invalid IP address, CIDR, or temporary block")],
  ["security.cors", { allowedOrigins: ["http://localhost:5173"], allowedMethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"], allowedHeaders: ["Content-Type", "Authorization", "X-Request-Id"], credentials: true, exposedHeaders: ["X-Request-Id"], preflightCacheSeconds: 600 }, (v) => v && stringList(origin, "origins")(v.allowedOrigins).valid && stringList((x) => ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"].includes(x), "HTTP methods")(v.allowedMethods).valid && stringList(headerName, "header names")(v.allowedHeaders).valid && stringList(headerName, "header names")(v.exposedHeaders).valid && integer(0, 86400)(v.preflightCacheSeconds).valid ? ok(v) : fail("contains invalid origins, methods, headers, or cache duration")],
  ["security.headers", { contentSecurityPolicy: "default-src 'none'; frame-ancestors 'none'", strictTransportSecurity: "max-age=15552000; includeSubDomains", frameOptions: "DENY", contentTypeOptions: "nosniff", referrerPolicy: "no-referrer", permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=()", crossOriginResourcePolicy: "same-site", crossOriginOpenerPolicy: "same-origin" }, "object"],
  ["security.csrf", { enabled: false, trustedOrigins: [] }, "object"], ["security.xss", { enabled: true }, "object"],
  ["security.cookies", { httpOnly: true, secure: true, sameSite: "strict", lifetimeMs: 604800000, prefix: "" }, (v) => v && ["strict", "lax", "none"].includes(v.sameSite) && duration(v.lifetimeMs).valid && /^[A-Za-z0-9_-]*$/.test(v.prefix) ? ok(v) : fail("contains invalid cookie security configuration")],
  ["security.trustedDevices", { enabled: false, lifetimeMs: 2592000000 }, "object"], ["security.trustedNetworks", [], (v) => stringList(cidr, "trusted network entries")(v)],
];
function registerSecuritySettings(registry) { DEFINITIONS.forEach(([key, defaultValue, validator], order) => { if (!registry.has(key)) registry.register({ key, label: key.split(".").slice(1).join(" "), group: "security", type: Array.isArray(defaultValue) ? "array" : "object", default: defaultValue, required: true, validator, description: "Runtime enterprise security policy.", ui: { section: key.split(".")[1], order } }); }); return registry; }
module.exports = { DEFINITIONS, registerSecuritySettings, cidr, origin };
