const crypto = require("crypto"); const zlib = require("zlib"); const mongoose = require("mongoose");
const settings = require("../settings"); const Validators = require("../settings/SettingValidators"); const SecretService = require("../security/IntegrationSecretService");
const Snapshot = require("../../models/ConfigurationSnapshot"); const Lock = require("../../models/ConfigurationLock"); const RuntimeSetting = require("../../models/RuntimeSetting"); const Version = require("../../models/RuntimeSettingVersion"); const Audit = require("../../models/RuntimeSettingAudit"); const Diff = require("./ConfigurationDiffEngine"); const { AppError } = require("../../utils/errorHandler");
const schemaVersion = 1; const platformVersion = process.env.npm_package_version || "1.0.0"; const canonical = (value) => JSON.stringify(value, Object.keys(value).sort()); const checksum = (value) => crypto.createHash("sha256").update(typeof value === "string" ? value : canonical(value)).digest("hex");
class ConfigurationManager {
  constructor({ maximumSnapshots = Number(process.env.CONFIG_MAX_SNAPSHOTS || 50), retentionDays = Number(process.env.CONFIG_RETENTION_DAYS || 90) } = {}) { if (!Number.isInteger(maximumSnapshots) || maximumSnapshots < 1 || maximumSnapshots > 1000) throw new Error("Maximum snapshots must be 1 to 1000."); if (!Number.isInteger(retentionDays) || retentionDays < 1 || retentionDays > 3650) throw new Error("Retention days must be 1 to 3650."); this.maximumSnapshots = maximumSnapshots; this.retentionDays = retentionDays; }
  async capture({ groups, keys, includeSecrets = true } = {}) { const selected = settings.definitions.list().filter((d) => (!groups || groups.includes(d.group)) && (!keys || keys.includes(d.key))); const payload = { schemaVersion, platformVersion, environment: process.env.NODE_ENV, exportedAt: new Date().toISOString(), settings: {} }; for (const definition of selected) { try { const result = await settings.get(definition.key, { withMetadata: true }); payload.settings[definition.key] = { value: definition.encrypted && !includeSecrets ? settings.encryption.mask(result.value) : result.value, encrypted: definition.encrypted, group: definition.group, version: result.version || null, source: result.source }; } catch (error) { if (error.code !== "SETTING_VALIDATION_FAILED") throw error; payload.settings[definition.key] = { value: null, encrypted: definition.encrypted, group: definition.group, version: null, source: "unconfigured", missing: true }; } } return payload; }
  pack(payload) { const raw = JSON.stringify(payload); const compressed = zlib.gzipSync(raw); return { envelope: SecretService.encrypt(compressed.toString("base64")), checksum: checksum(raw), sizeBytes: compressed.length }; }
  unpack(envelope) { const compressed = Buffer.from(SecretService.decrypt(envelope), "base64"); return JSON.parse(zlib.gunzipSync(compressed).toString("utf8")); }
  async audit(event, context = {}, metadata = {}) { if (mongoose.connection.readyState === 1) await Audit.create({ event, key: "configuration", group: "configuration", actorId: context.actorId || null, requestId: context.requestId || "", ip: context.ip || "", metadata }); }
  async list({ search = "", type = "", limit = 100 } = {}) { if (mongoose.connection.readyState !== 1) return []; const filter = {}; if (type) filter.type = type; if (search) filter.$or = [{ version: { $regex: search, $options: "i" } }, { description: { $regex: search, $options: "i" } }]; return Snapshot.find(filter).populate("createdBy", "name email").sort({ createdAt: -1 }).limit(Math.min(Number(limit) || 100, 500)).lean(); }
  async backup(options = {}, context = {}) { if (mongoose.connection.readyState !== 1) throw new AppError("Database connection is required for configuration backup.", 503); const payload = await this.capture({ groups: options.groups, keys: options.keys, includeSecrets: true }); const packed = this.pack(payload); const latest = await Snapshot.findOne().sort({ createdAt: -1 }).lean(); const diff = latest ? Diff.compare(this.unpack((await Snapshot.findById(latest._id).select("+payload")).payload), payload) : { changed: Object.keys(payload.settings).map((key) => ({ key })) }; const changedKeys = [...diff.added || [], ...diff.removed || [], ...diff.changed || []].map((x) => x.key); const version = `cfg-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`; const snapshot = await Snapshot.create({ version, description: options.description || "Manual configuration backup", type: options.type || "manual", payload: packed.envelope, checksum: packed.checksum, environment: payload.environment, platformVersion, schemaVersion, groups: [...new Set(Object.values(payload.settings).map((x) => x.group))], keys: Object.keys(payload.settings), changedKeys, changedGroups: [...new Set(changedKeys.map((key) => payload.settings[key]?.group).filter(Boolean))], parentSnapshotId: latest?._id || null, sizeBytes: packed.sizeBytes, expiresAt: new Date(Date.now() + this.retentionDays * 86400000), createdBy: context.actorId || null }); await this.verify(snapshot._id); await this.cleanup(context); await this.audit("configuration.backup.created", context, { snapshotId: snapshot._id, version, checksum: packed.checksum, type: snapshot.type }); return snapshot.toObject(); }
  validatePayload(payload, { allowMaskedSecrets = false } = {}) { const errors = []; if (payload?.schemaVersion !== schemaVersion) errors.push("Unsupported schema version."); if (!payload?.settings || typeof payload.settings !== "object") errors.push("Settings payload is missing."); for (const [key, item] of Object.entries(payload?.settings || {})) { const definition = settings.definitions.get(key); if (!definition) errors.push(`Unknown setting: ${key}`); else { if (item.group && item.group !== definition.group) errors.push(`Invalid group for ${key}.`); if (item.missing === true && item.value === null) continue; if (definition.encrypted && /^\*+$/.test(String(item.value)) && !allowMaskedSecrets) errors.push(`Encrypted secret ${key} is masked.`); try { if (!(definition.encrypted && /^\*+$/.test(String(item.value)))) Validators.validate(definition, item.value); } catch (error) { errors.push(`${key}: ${error.message}`); } } } return { valid: errors.length === 0, errors, schemaVersion: payload?.schemaVersion, settings: Object.keys(payload?.settings || {}).length }; }
  async verify(id) { const snapshot = await Snapshot.findById(id).select("+payload"); if (!snapshot) throw new AppError("Configuration snapshot not found.", 404); try { const payload = this.unpack(snapshot.payload); const raw = JSON.stringify(payload); const validation = this.validatePayload(payload); const valid = checksum(raw) === snapshot.checksum && validation.valid; if (!valid) await this.audit("configuration.integrity.failed", {}, { snapshotId: id, checksumValid: checksum(raw) === snapshot.checksum, errors: validation.errors }); if (valid) { snapshot.verifiedAt = new Date(); await snapshot.save(); } return { valid, checksumValid: checksum(raw) === snapshot.checksum, validation, snapshotId: id }; } catch (error) { await this.audit("configuration.integrity.failed", {}, { snapshotId: id, error: error.message }); return { valid: false, checksumValid: false, errors: [error.message], snapshotId: id }; } }
  async snapshotPayload(id) { const snapshot = await Snapshot.findById(id).select("+payload"); if (!snapshot) throw new AppError("Configuration snapshot not found.", 404); return { snapshot, payload: this.unpack(snapshot.payload) }; }
  async currentPayload() { return this.capture({ includeSecrets: true }); }
  async diff({ left = "current", right, imported } = {}) { const resolve = async (ref, value) => value || (ref === "current" ? this.currentPayload() : (await this.snapshotPayload(ref)).payload); if (!right && !imported) throw new AppError("A comparison target is required.", 422); return Diff.compare(await resolve(left), await resolve(right || "import", imported)); }
  async acquire(operation, owner) { if (mongoose.connection.readyState !== 1) throw new AppError("Database connection is required.", 503); const now = new Date(), expiresAt = new Date(Date.now() + 10 * 60000); const lock = await Lock.findOneAndUpdate({ key: "global", $or: [{ locked: false }, { expiresAt: { $lt: now } }, { locked: { $exists: false } }] }, { $set: { locked: true, operation, owner, lockedAt: now, expiresAt } }, { new: true, upsert: true }).catch((error) => { if (error.code === 11000) return null; throw error; }); if (!lock) throw new AppError("Another configuration import or restore is already running.", 423); if (lock.readOnly) { await this.release(owner); throw new AppError("Configuration is read-only.", 423); } if (lock.maintenanceLock && operation !== "recovery") { await this.release(owner); throw new AppError("Configuration maintenance lock is active.", 423); } return lock; }
  async release(owner) { await Lock.updateOne({ key: "global", owner }, { $set: { locked: false, operation: "", owner: "", lockedAt: null, expiresAt: null } }); }
  async apply(payload, scope = {}, context = {}) { const validation = this.validatePayload(payload); if (!validation.valid) throw new AppError(`Configuration validation failed: ${validation.errors.join("; ")}`, 422); const selected = Object.entries(payload.settings).filter(([key, item]) => !item.missing && (!scope.group || item.group === scope.group) && (!scope.key || key === scope.key)); for (const [key, item] of selected) await settings.set(key, item.value, { ...context, auditEvent: "setting.updated", metadata: { lifecycleOperation: context.operation } }); settings.clearCache({ keys: selected.map(([key]) => key), context }); return selected.map(([key]) => key); }
  async restore(id, options = {}, context = {}) { const current = await this.currentPayload(); const { payload } = await this.snapshotPayload(id); const preview = Diff.compare(current, payload); if (options.preview) return { preview, snapshotId: id }; if (options.confirm !== true) throw new AppError("Restore confirmation is required.", 422); const owner = `${context.actorId}:${crypto.randomUUID()}`; await this.acquire("restore", owner); const pre = await this.backup({ type: "pre_restore", description: `Automatic backup before restoring ${id}` }, context); try { const changedKeys = await this.apply(payload, { group: options.group, key: options.key }, { ...context, operation: "restore" }); await this.audit("configuration.restored", context, { snapshotId: id, changedKeys, scope: options.group || options.key || "all" }); return { restored: true, snapshotId: id, changedKeys, preRestoreSnapshotId: pre._id, preview }; } catch (error) { await this.apply(current, {}, { ...context, operation: "automatic_rollback" }); throw error; } finally { await this.release(owner); } }
  async rollback(id, options = {}, context = {}) { if (options.confirm !== true) throw new AppError("Rollback confirmation is required.", 422); const result = await this.restore(id, options, context); await this.audit("configuration.rollback", context, { snapshotId: id, changedKeys: result.changedKeys }); return result; }
  async export(options = {}, context = {}) { const payload = await this.capture({ groups: options.groups, keys: options.keys, includeSecrets: Boolean(options.includeSecrets) }); await this.audit("configuration.exported", context, { groups: options.groups || [], keys: options.keys || [], encrypted: options.encrypted !== false, includesSecrets: Boolean(options.includeSecrets) }); if (options.encrypted !== false) { const packed = this.pack(payload); return { format: "encrypted-json", schemaVersion, checksum: packed.checksum, compressed: true, encrypted: true, payload: packed.envelope }; } if (options.includeSecrets !== true) return payload; return payload; }
  decodeImport(input) { if (input?.format === "encrypted-json") { const payload = this.unpack(input.payload); if (checksum(JSON.stringify(payload)) !== input.checksum) throw new AppError("Imported backup checksum is invalid.", 422); return payload; } return input; }
  async import(input, options = {}, context = {}) { const payload = this.decodeImport(input); const validation = this.validatePayload(payload); if (options.preview) return { validation, diff: await this.diff({ imported: payload }) }; if (options.confirm !== true) throw new AppError("Import confirmation is required.", 422); const owner = `${context.actorId}:${crypto.randomUUID()}`; await this.acquire("import", owner); const current = await this.currentPayload(); try { await this.backup({ type: "pre_restore", description: "Automatic backup before configuration import" }, context); const changedKeys = await this.apply(payload, {}, { ...context, operation: "import" }); await this.backup({ type: "import", description: options.description || "Imported configuration" }, context); await this.audit("configuration.imported", context, { changedKeys }); return { imported: changedKeys.length, changedKeys }; } catch (error) { await this.apply(current, {}, { ...context, operation: "import_rollback" }); throw error; } finally { await this.release(owner); } }
  async versions({ key, group, limit = 200 } = {}) { if (mongoose.connection.readyState !== 1) return []; const filter = {}; if (key) filter.key = key; if (group) filter.group = group; return Version.find(filter).populate("actorId", "name email").sort({ createdAt: -1 }).limit(Math.min(Number(limit) || 200, 500)).lean(); }
  async recover(action, options = {}, context = {}) { if (options.confirm !== true) throw new AppError("Recovery confirmation is required.", 422); let report; if (["latest", "emergency", "safe_mode"].includes(action)) { const latest = await Snapshot.findOne().sort({ createdAt: -1 }); if (!latest) throw new AppError("No configuration backup is available.", 404); report = await this.restore(latest._id, { confirm: true, group: action === "safe_mode" ? "security" : undefined }, context); } else if (action === "reset") { const owner = `${context.actorId}:${crypto.randomUUID()}`; await this.acquire("reset", owner); try { const backup = await this.backup({ type: "recovery", description: "Automatic backup before configuration reset" }, context); await RuntimeSetting.deleteMany({}); settings.clearCache({ context }); report = { reset: true, backupId: backup._id }; } finally { await this.release(owner); } } else throw new AppError("Unsupported recovery action.", 422); await this.audit("configuration.recovery.executed", context, { action, report }); return { action, report, validated: true, completedAt: new Date() }; }
  async remove(id, context = {}) { const removed = await Snapshot.findByIdAndDelete(id); if (!removed) throw new AppError("Snapshot not found.", 404); await this.audit("configuration.backup.deleted", context, { snapshotId: id, version: removed.version }); return true; }
  async cleanup(context = {}) { if (mongoose.connection.readyState !== 1) return { removed: 0 }; const now = new Date(); const expired = await Snapshot.deleteMany({ expiresAt: { $lte: now } }); const excess = await Snapshot.find().sort({ createdAt: -1 }).skip(this.maximumSnapshots).select("_id").lean(); if (excess.length) await Snapshot.deleteMany({ _id: { $in: excess.map((x) => x._id) } }); const removed = expired.deletedCount + excess.length; if (removed) await this.audit("configuration.backup.deleted", context, { automatic: true, removed }); return { removed, maximumSnapshots: this.maximumSnapshots, retentionDays: this.retentionDays }; }
  async overview() { const snapshots = await this.list({ limit: 20 }); const lock = mongoose.connection.readyState === 1 ? await Lock.findOne({ key: "global" }).lean() : null; return { snapshots, snapshotCount: mongoose.connection.readyState === 1 ? await Snapshot.countDocuments() : 0, latest: snapshots[0] || null, retention: { maximumSnapshots: this.maximumSnapshots, retentionDays: this.retentionDays }, lock: lock || { locked: false, readOnly: false, maintenanceLock: false }, encryption: SecretService.encryptionStatus(), schemaVersion, platformVersion }; }
}
module.exports = new ConfigurationManager(); module.exports.ConfigurationManager = ConfigurationManager; module.exports.checksum = checksum;
