const DEFAULT_SETTINGS = [
  {
    key: "general.siteName",
    group: "General",
    value: "Parentheses Licensing Portal",
    type: "string",
    isPublic: true,
    description: "Display name reserved for future portal branding controls.",
    reservedFor: "Phase 7B",
  },
  {
    key: "licensing.defaultStatus",
    group: "Licensing",
    value: "active",
    type: "string",
    description: "Reserved for future default license status behavior.",
    reservedFor: "Phase 7C",
  },
  {
    key: "downloads.maxPluginZipMB",
    group: "Downloads",
    value: 50,
    type: "number",
    description: "Reserved for future configurable upload size limits.",
    reservedFor: "Phase 7C",
  },
  {
    key: "payments.defaultCurrency",
    group: "Payments",
    value: "USD",
    type: "string",
    description: "Reserved for future payment display defaults.",
    reservedFor: "Phase 7B",
  },
  {
    key: "email.fromName",
    group: "Email",
    value: "Parentheses Solutions",
    type: "string",
    description: "Reserved for future email template defaults.",
    reservedFor: "Phase 7B",
  },
  {
    key: "email.smtpPassword",
    group: "Email",
    value: null,
    type: "string",
    isSecret: true,
    envKey: "SMTP_PASS",
    description: "SMTP password remains env-managed until encrypted settings storage exists.",
    reservedFor: "Phase 7B",
  },
  {
    key: "notifications.defaultSender",
    group: "Notifications",
    value: "Parentheses <no-reply@example.com>",
    type: "string",
    description: "Default sender label for notification templates when env SMTP_FROM is not customized.",
    reservedFor: "Phase 10I",
  },
  {
    key: "notifications.replyTo",
    group: "Notifications",
    value: "support@example.com",
    type: "string",
    description: "Default reply-to address used by outbound notification emails.",
    reservedFor: "Phase 10I",
  },
  {
    key: "notifications.inAppEnabled",
    group: "Notifications",
    value: true,
    type: "boolean",
    description: "Controls whether in-app notification records are available for customer and admin communication flows.",
    reservedFor: "Phase 10I",
  },
  {
    key: "payments.stripeSecretKey",
    group: "Payments",
    value: null,
    type: "string",
    isSecret: true,
    envKey: "STRIPE_SECRET_KEY",
    description: "Stripe secret key remains env-managed until encrypted settings storage exists.",
    reservedFor: "Phase 7B",
  },
  {
    key: "payments.stripeWebhookSecret",
    group: "Payments",
    value: null,
    type: "string",
    isSecret: true,
    envKey: "STRIPE_WEBHOOK_SECRET",
    description: "Stripe webhook secret remains env-managed until encrypted settings storage exists.",
    reservedFor: "Phase 7B",
  },
  {
    key: "security.requireStrongPasswords",
    group: "Security",
    value: true,
    type: "boolean",
    description: "Reserved for future password policy controls.",
    reservedFor: "Phase 7C",
  },
  {
    key: "wordpressUpdater.releaseChannel",
    group: "WordPress Updater",
    value: "stable",
    type: "string",
    description: "Reserved for future WordPress updater release channels.",
    reservedFor: "Phase 7C",
  },
  {
    key: "maintenance.maintenanceMode",
    group: "Maintenance",
    value: false,
    type: "boolean",
    description: "Reserved for future maintenance mode.",
    reservedFor: "Phase 7C",
  },
];

module.exports = { DEFAULT_SETTINGS };
