const { AppError } = require("../utils/errorHandler");
const runtime = require("../services/security/SecurityRuntime");
const { checkRateLimit } = require("./rateLimiter");
function ipv4Number(ip) { const parts = String(ip).replace(/^::ffff:/, "").split("."); return parts.length === 4 && parts.every((x) => /^\d+$/.test(x) && Number(x) <= 255) ? parts.reduce((n, x) => (n * 256) + Number(x), 0) >>> 0 : null; }
function matches(ip, entry) { const [network, bitsText] = String(entry).split("/"); if (!bitsText) return String(ip).replace(/^::ffff:/, "") === network; const value = ipv4Number(ip), base = ipv4Number(network), bits = Number(bitsText); if (value === null || base === null) return false; const mask = bits === 0 ? 0 : (0xffffffff << (32 - bits)) >>> 0; return (value & mask) === (base & mask); }
async function load(req, res, next) { return runtime.middleware(req, res, next); }
function protectIp(req, res, next) { const policy = runtime.value("security.ip", {}); const now = Date.now(); const blocked = [...(policy.blockList || []), ...(policy.permanentBlocks || []), ...(policy.temporaryBlocks || []).filter((x) => Date.parse(x.expiresAt) > now).map((x) => x.value)]; if (blocked.some((x) => matches(req.ip, x))) return next(new AppError("This IP address is blocked by security policy.", 403)); if ((policy.allowList || []).length && !policy.allowList.some((x) => matches(req.ip, x))) return next(new AppError("This IP address is not allowed by security policy.", 403)); next(); }
function headers(req, res, next) { const h = runtime.value("security.headers", {}); const map = { contentSecurityPolicy: "Content-Security-Policy", strictTransportSecurity: "Strict-Transport-Security", frameOptions: "X-Frame-Options", contentTypeOptions: "X-Content-Type-Options", referrerPolicy: "Referrer-Policy", permissionsPolicy: "Permissions-Policy", crossOriginResourcePolicy: "Cross-Origin-Resource-Policy", crossOriginOpenerPolicy: "Cross-Origin-Opener-Policy" }; Object.entries(map).forEach(([key, name]) => h[key] ? res.setHeader(name, h[key]) : res.removeHeader(name)); next(); }
function rate(policyName) { return async (req, res, next) => { const policy = runtime.value(`security.rateLimits.${policyName}`, { enabled: true, limit: 300, burst: 0, windowMs: 900000 }); if (!policy.enabled) return next(); const result = await checkRateLimit(`runtime:${policyName}:${req.ip}`, { maxRequests: policy.limit + policy.burst, windowMs: policy.windowMs }); res.setHeader("X-RateLimit-Remaining", result.remaining); if (!result.allowed) return res.status(429).json({ success: false, message: "Too many requests. Please slow down.", retryAfter: Math.ceil((result.resetAt - Date.now()) / 1000) }); next(); }; }
module.exports = { load, protectIp, headers, rate, matches };
