import { useMemo, useState } from "react";
import { Button, Input } from "../../components/ui";
import { useFeatureFlagAction, useFeatureFlags, useMaintenanceStatus } from "../../hooks/useSettings";
const CATEGORIES = ["core", "licensing", "payments", "email", "ai", "storage", "security", "downloads", "plugin_updates", "reports", "admin_tools", "developer_tools", "experimental", "maintenance", "future_modules"];
export default function FeatureFlagCenterSection() {
  const { data: flags = [], isLoading } = useFeatureFlags(); const { data: maintenance } = useMaintenanceStatus(); const action = useFeatureFlagAction(); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [selected, setSelected] = useState([]);
  const visible = useMemo(() => flags.filter((flag) => (!category || flag.category === category) && `${flag.name} ${flag.key}`.toLowerCase().includes(search.toLowerCase())), [flags, category, search]);
  const toggleSelected = (key) => setSelected((old) => old.includes(key) ? old.filter((x) => x !== key) : [...old, key]);
  if (isLoading) return <section className="card p-5">Loading Feature Flag Center…</section>;
  return <section className="space-y-4"><div className="card p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-semibold">Feature Flags &amp; Runtime Toggles</h2><p className="text-sm text-gray-500">Controlled rollouts, dependencies, schedules, maintenance, and emergency switches.</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-semibold ${maintenance?.enabled ? "bg-amber-100 text-amber-800" : "bg-green-100 text-green-800"}`}>Maintenance {maintenance?.enabled ? "enabled" : "disabled"}</span></div><div className="grid md:grid-cols-[1fr_220px_auto_auto] gap-2"><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search features…"/><select className="input" value={category} onChange={(e) => setCategory(e.target.value)}><option value="">All categories</option>{CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select><Button disabled={!selected.length || action.isPending} onClick={() => action.mutate({ action: "bulk", keys: selected, changes: { enabled: true } })}>Enable selected</Button><Button disabled={!selected.length || action.isPending} onClick={() => action.mutate({ action: "bulk", keys: selected, changes: { enabled: false } })}>Disable selected</Button></div></div><div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left"><tr><th className="p-3"></th><th className="p-3">Feature</th><th className="p-3">Category</th><th className="p-3">Status</th><th className="p-3">Rollout</th><th className="p-3">Dependencies</th><th className="p-3">Environment</th><th className="p-3">Last updated</th><th className="p-3">Actions</th></tr></thead><tbody>{visible.map((flag) => <FlagRow key={flag.key} flag={flag} selected={selected.includes(flag.key)} toggleSelected={toggleSelected} action={action}/>)}</tbody></table></div><div className="card p-4 flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">Maintenance mode</h3><p className="text-sm text-gray-500">{maintenance?.message}</p></div><Button disabled={action.isPending} onClick={() => action.mutate({ action: "maintenance", payload: { ...maintenance, enabled: !maintenance?.enabled } })}>{maintenance?.enabled ? "Disable maintenance" : "Enable maintenance"}</Button></div></section>;
}
function FlagRow({ flag, selected, toggleSelected, action }) { const [rollout, setRollout] = useState(flag.rolloutPercentage ?? 100); const environment = (flag.environmentRules || []).map((x) => `${x.environment}:${x.enabled ? "on" : "off"}`).join(", ") || "All"; return <tr className="border-t align-top"><td className="p-3"><input type="checkbox" checked={selected} onChange={() => toggleSelected(flag.key)}/></td><td className="p-3"><p className="font-medium">{flag.name}</p><p className="font-mono text-xs text-gray-500">{flag.key}</p><p className="text-xs text-gray-400">{flag.updatedBy?.name || "System"}</p></td><td className="p-3">{flag.category}</td><td className="p-3"><span className={flag.enabled ? "text-green-700" : "text-gray-500"}>{flag.enabled ? "Enabled" : "Disabled"}</span>{flag.emergencyKillSwitch && <p className="text-xs text-red-600">Kill switch active</p>}</td><td className="p-3"><select className="border rounded px-2 py-1" value={rollout} onChange={(e) => setRollout(Number(e.target.value))}>{[0,5,10,25,50,75,100].map((x) => <option key={x} value={x}>{x}%</option>)}</select><Button className="mt-1" disabled={rollout === flag.rolloutPercentage} onClick={() => action.mutate({ action: "patch", key: flag.key, payload: { rolloutPercentage: rollout } })}>Save</Button></td><td className="p-3 text-xs">{flag.dependencies?.join(", ") || "None"}</td><td className="p-3 text-xs">{environment}</td><td className="p-3 text-xs">{flag.updatedAt ? new Date(flag.updatedAt).toLocaleString() : "Default"}</td><td className="p-3 space-y-1"><Button onClick={() => action.mutate({ action: flag.enabled ? "disable" : "enable", key: flag.key })}>{flag.enabled ? "Disable" : "Enable"}</Button><Button onClick={() => action.mutate({ action: "patch", key: flag.key, payload: { emergencyKillSwitch: !flag.emergencyKillSwitch } })}>{flag.emergencyKillSwitch ? "Clear kill switch" : "Kill switch"}</Button></td></tr>; }
