import { useEffect, useMemo, useState } from "react";
import { Button } from "../../components/ui";
import { useSecurityAction, useSecurityCenter, useSecurityHealth } from "../../hooks/useSettings";
const ORDER = ["authentication", "password", "sessions", "jwt", "rateLimits", "bruteForce", "cors", "ip", "headers", "cookies", "csrf", "xss", "trustedDevices", "trustedNetworks"];
const title = (value) => value.replace(/([A-Z])/g, " $1").replace(/^./, (x) => x.toUpperCase());
export default function SecurityCenterSection() {
  const { data = {}, isLoading } = useSecurityCenter(); const { data: health } = useSecurityHealth(); const action = useSecurityAction();
  const initial = useMemo(() => Object.fromEntries(Object.entries(data).map(([key, item]) => [key, JSON.stringify(item.value, null, 2)])), [data]);
  const [forms, setForms] = useState({}); const [errors, setErrors] = useState({}); useEffect(() => setForms(initial), [initial]);
  const save = (key) => { try { const value = JSON.parse(forms[key]); setErrors((old) => ({ ...old, [key]: "" })); action.mutate({ action: "save", payload: { [key]: value } }); } catch { setErrors((old) => ({ ...old, [key]: "Enter valid JSON." })); } };
  if (isLoading) return <section className="card p-5">Loading Security Center…</section>;
  const entries = Object.entries(data).sort(([a], [b]) => ORDER.indexOf(a.split(".")[1]) - ORDER.indexOf(b.split(".")[1]));
  return <section className="space-y-4"><div className="card p-5 flex flex-wrap justify-between gap-4"><div><h2 className="font-semibold text-lg">Security &amp; Authentication Center</h2><p className="text-sm text-gray-500">Runtime authentication, sessions, network controls, headers, cookies, and request protection.</p></div><div className="text-right"><p className="text-3xl font-bold text-brand-600">{health?.overallSecurityScore ?? "—"}%</p><p className="text-xs text-gray-500">Overall security score</p></div></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{entries.map(([key, item]) => <article className="card p-4 space-y-3" key={key}><div><h3 className="font-semibold">{title(key.replace("security.", ""))}</h3><p className="text-xs text-gray-500">Source: {item.source}</p></div><textarea aria-label={key} className="w-full min-h-56 border rounded-lg p-3 font-mono text-xs" value={forms[key] ?? ""} onChange={(event) => setForms((old) => ({ ...old, [key]: event.target.value }))} />{errors[key] && <p className="text-xs text-red-600">{errors[key]}</p>}<Button disabled={action.isPending || forms[key] === initial[key]} onClick={() => save(key)}>Save policy</Button></article>)}</div><div className="card p-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Session invalidation</h3><p className="text-sm text-gray-500">Immediately revoke every active refresh session.</p></div><Button disabled={action.isPending} onClick={() => window.confirm("Force logout all users?") && action.mutate({ action: "forceLogout" })}>Force logout</Button></div></section>;
}
